openapi: 3.0.0
info:
  title: Colossus.AI Authentication API
  version: 1.0.0
  description: API documentation for authentication endpoints

servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /auth/signup:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
              required:
                - username
                - email
                - password
                - confirmPassword
      responses:
        201:
          description: User created successfully
        400:
          description: Validation error or user already exists
        500:
          description: Server error

  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emailOrUsername:
                  type: string
                password:
                  type: string
              required:
                - emailOrUsername
                - password
      responses:
        200:
          description: Login successful
        401:
          description: Invalid credentials
        500:
          description: Server error

  /auth/reset-password:
    post:
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        200:
          description: Reset pin sent
        404:
          description: User not found
        500:
          description: Server error

  /auth/verify-pin:
    post:
      summary: Verify reset pin and update password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                pin:
                  type: string
                newPassword:
                  type: string
                confirmPassword:
                  type: string
              required:
                - email
                - pin
                - newPassword
                - confirmPassword
      responses:
        200:
          description: Password updated successfully
        400:
          description: Invalid or expired pin
        500:
          description: Server error
# Add this to your existing swagger.yaml paths
  /auth/google:
    post:
      summary: Authenticate with Google
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: Google OAuth authorization code
              required:
                - code
      responses:
        200:
          description: Google authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
        400:
          description: Invalid Google token
        500:
          description: Server error
