import { Inter } from 'next/font/google'
import "./globals.css"
import { AppSidebar } from "@/components/app-sidebar"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'reactflow/dist/style.css'

const inter = Inter({ subsets: ["latin"] })

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Colossus AI",
  description: "Generated by create next app",
};
export const metadata = {
  title: "Modern Chatbot",
  description: "A modern chatbot interface with file attachments and knowledge graph",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossOrigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossOrigin="anonymous"></script>
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
        {children}
      <body className={inter.className}>
        <div className="relative min-h-screen">
          <AppSidebar />
          <main className="p-4 sm:p-6 md:p-8">
            {children}
          </main>
        </div>
        
      </body>
    </html>
  )
}

